add-retries
pikselpalette/sequoia-python-client-sdk-async pull request #2
Opened 2020-04-14 07:10 UTC by paco-piksel

Add backoff dependency and simple code to be able to retry each call to httpx.send request

2020-04-14 09:51 UTC, perdy requested changes

2020-04-14 09:51 UTC, perdy commented on sequoia/request.py
> +        backoff.expo, httpx.exceptions.TimeoutException, max_tries=10, logger=logger,
I'd say that ten tries is probably excessive, 2-3 are the common numbers. Probably we don't want to catch only TimoutException but a generic Exception (or even a less generic HTTPError from httpx)

2020-04-14 09:51 UTC, perdy commented on sequoia/request.py
> +    async def _request_with_retry(self, request: Request) -> Response:
Shouldn't we decorate the main request method instead of wrapping it? Or said with other words: doesn't we want to all our requests being retried if fail?

2020-04-14 09:51 UTC, perdy commented on sequoia/request.py
> +        return await self._httpx_client.send(request=request)
Make some tests! (and update the current tests)

2020-04-14 10:03 UTC, paco-piksel commented on sequoia/request.py
> +        backoff.expo, httpx.exceptions.TimeoutException, max_tries=10, logger=logger,
Perhaps 10 attempts is excessive but the servers I'm hitting are quite unreliable... how about 5 as an agreement?
Regarding the type of exception to capture, I'm pretty sure I want to re-try when there is a timeout... not so sure when there are other kind of errors... I guess there is no harm though so I will change it by HTTPError

2020-04-14 10:08 UTC, paco-piksel commented on sequoia/request.py
> +    async def _request_with_retry(self, request: Request) -> Response:
not sure I get you... all our request are sent using _request method so with this change all requests are going to be retried when they fail, don't they?
and regarding decorate the whole request method... we can do it but I don't want/need re-build the request on each retry... what's the benefit on decorating _request? or am I understanding you wrong?

2020-04-14 10:08 UTC, paco-piksel commented on sequoia/request.py
> +        return await self._httpx_client.send(request=request)
I was thinking about this... aren't we going to test only backoff library?

2020-04-14 10:34 UTC, perdy commented on sequoia/request.py
> +        backoff.expo, httpx.exceptions.TimeoutException, max_tries=10, logger=logger,
5, fair enough.

Lets think about a filtering request (with pagination) so if any of the requests (one per page) fails with a 5xx, due to server overload, shouldn't we retry it? IMHO it doesn't harm to retry any HTTPError due to any reason.

2020-04-14 10:36 UTC, perdy commented on sequoia/request.py
> +        return await self._httpx_client.send(request=request)
Probably there are some negative tests cases that you'd need to modify, because now they're going to be retried. Also it's a good idea to modify retrying mechanism in tests to avoid it in all tests (except in those where we want to test the retrying mechanism) to make tests faster (not retrying and sleeping).

2020-04-14 10:38 UTC, perdy commented on sequoia/request.py
> +    async def _request_with_retry(self, request: Request) -> Response:
Ah, I missread the code, you're right !

2020-04-16 07:16 UTC, paco-piksel commented on sequoia/request.py
> +        backoff.expo, httpx.exceptions.TimeoutException, max_tries=10, logger=logger,
As we also agreed to provide a way to configure the number of retries in Client, I've set 3 as default value. I'll set 5 in my client config.

2020-04-20 09:58 UTC, perdy approved these changes

2020-04-20 10:02 UTC, merged